[package]
name = "ksud"
version = "0.1.0"
edition = "2021"
rust-version = "1.76"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.2", features = ["derive"] }
const_format = "0.2.32"
zip = "0.6.6"
zip-extensions = "0.6.2"
java-properties = "2.0.0"
log = "0.4.21"
env_logger = "0.11.3"
serde = { version = "1.0.197" }
serde_json = "1.0.114"
regex = "1.10.3"
encoding_rs = "0.8.33"
retry = "2.0.0"
humansize = "2.1.3"
libc = "0.2.153"
extattr = "1.0.0"
jwalk = "0.8.1"
is_executable = "1.0.1"
nom = "7.1.3"
derive-new = "0.6.0"
rust-embed = { version = "8.3.0", features = [
    "debug-embed",
    "compression", # must clean build after updating binaries
] }
which = "6.0.0"
getopts = "0.2.21"
sha256 = "1.5.0"
tempdir = "0.3.7"
chrono = "0.4.35"
hole-punch = { git = "https://github.com/tiann/hole-punch" }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
rustix = { git = "https://github.com/Kernel-SU/rustix.git", branch = "main", features = ["all-apis"] }
# some android specific dependencies which compiles under unix are also listed here for convenience of coding
android-properties = { version = "0.2.2", features = ["bionic-deprecated"] }
procfs = "0.16.0"
loopdev = { git = "https://github.com/Kernel-SU/loopdev" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.3"

[profile.release]
strip = true
opt-level = "z"
lto = true
