name: Build Userspace
on:
  push:
    branches: [ "main", "fix-ci" ]
    paths: 
      - '.github/workflows/build-userspace.yml'
      - 'userspace/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'userspace/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        local-cache: true
    - name: Build su
      working-directory: ./userspace/su
      run: ndk-build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: su
        path: ./userspace/su/libs
    - name: Build aarch64 ksud
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        target: aarch64-linux-android
        override: true
    - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-linux-android --release
    - name: Upload aarch64 ksud Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ksud-arm64
        path: ./userspace/ksud/target/aarch64-linux-android/release/ksud

