name: Build Kernel 5.10
on:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/build-kernel-5.10.yml'
      - 'kernel/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'kernel/**'
jobs:
  build:
    strategy:
      matrix:
        include:
          - version: 66
            os_patch_level: 2021-11
          - version: 81
            os_patch_level: 2022-03
          - version: 101
            os_patch_level: 2022-05
          - version: 110
            os_patch_level: 2022-07
          - version: 136
            os_patch_level: 2022-11
    uses: ./.github/workflows/gki-kernel.yml
    with:
      out_dir: android12-5.10
      version: android12-5.10-${{ matrix.version }}
      tag: android12-5.10-${{ matrix.os_patch_level }}
      os_version: 12.0.0
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: 5.10