name: Build Kernel - Android 12
on:
  push:
    branches: ["main", "ci"]
    paths:
      - ".github/workflows/build-kernel-a12.yml"
      - ".github/workflows/gki-kernel.yml"
      - "kernel/**"
  pull_request:
    branches: ["main"]
    paths:
      - "kernel/**"
jobs:
  build:
    strategy:
      matrix:
        include:
          - sub_level: 66
            os_patch_level: 2021-11
          - sub_level: 81
            os_patch_level: 2022-03
          - sub_level: 101
            os_patch_level: 2022-05
          - sub_level: 110
            os_patch_level: 2022-07
          - sub_level: 136
            os_patch_level: 2022-11
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android12-5.10
      version_name: android12-5.10.${{ matrix.sub_level }}
      tag: android12-5.10-${{ matrix.os_patch_level }}
      os_version: 12.0.0
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: "5.10"
