name: Build Manager
on:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/build-manager.yml'
      - 'manager/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'manager/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manager
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Extract keystore
      if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/main' ) || github.ref_type == 'tag' }}
      run: |
        if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
          echo KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' >> sign.properties
          echo KEY_ALIAS='${{ secrets.KEY_ALIAS }}' >> sign.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> sign.properties
          echo KEYSTORE_FILE='../key.jks' >> sign.properties
          echo ${{ secrets.KEYSTORE }} | base64 --decode > key.jks
        fi
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: manager
        path: manager/app/build/outputs/apk/release/*.apk
    
