name: Build SU
on:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/build-su.yml'
      - 'userspace/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'userspace/**'
jobs:
  build-su:
    name: Build userspace su
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        local-cache: true
    - name: Build su
      working-directory: ./userspace/su
      run: ndk-build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: su
        path: ./userspace/su/libs
    - name: Upload to telegram
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        CACHE_CHAT_ID: ${{ secrets.CACHE_CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
      run: |
        pip3 install python-telegram-bot
        mv ./userspace/su/libs/arm64-v8a/su su-arm64
        mv ./userspace/su/libs/x86_64/su su-x86_64
        python3 scripts/ksubot.py su-arm64 su-x86_64
