name: Build Kernel - Android 13
on:
  push:
    branches: ["main", "ci"]
    paths:
      - ".github/workflows/build-kernel-a13.yml"
      - ".github/workflows/gki-kernel.yml"
      - "kernel/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build-kernel-a13.yml"
      - ".github/workflows/gki-kernel.yml"
      - "kernel/**"
jobs:
  build-ksud:
    uses: ./.github/workflows/ksud.yml
    with:
      target: aarch64-linux-android
  build-kernel:
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        include:
          - version: "5.10"
            sub_level: 107
            os_patch_level: 2022-11
          - version: "5.15"
            sub_level: 41
            os_patch_level: 2022-11
          - version: "5.15"
            sub_level: 74
            os_patch_level: 2022-12
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android13-${{ matrix.version }}
      version_name: android13-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android13-${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_version: 13.0.0
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}
  check-build-kernel:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        include:
          - version: "5.10"
            sub_level: 107
            os_patch_level: 2022-11
          - version: "5.15"
            sub_level: 41
            os_patch_level: 2022-11
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android13-${{ matrix.version }}
      version_name: android13-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android13-${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_version: 13.0.0
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}