name: Build Kernel - Android 12
on:
  push:
    branches: ["main", "ci"]
    paths:
      - ".github/workflows/build-kernel-a12.yml"
      - ".github/workflows/gki-kernel.yml"
      - "kernel/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build-kernel-a12.yml"
      - ".github/workflows/gki-kernel.yml"
      - "kernel/**"
jobs:
  build-ksud:
    uses: ./.github/workflows/ksud.yml
    with:
      target: aarch64-linux-android
  build-kernel:
    needs: build-ksud
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        include:
          - sub_level: 66
            os_patch_level: 2021-11
          - sub_level: 81
            os_patch_level: 2022-03
          - sub_level: 101
            os_patch_level: 2022-05
          - sub_level: 110
            os_patch_level: 2022-07
          - sub_level: 136
            os_patch_level: 2022-11
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android12-5.10
      version_name: android12-5.10.${{ matrix.sub_level }}
      tag: android12-5.10-${{ matrix.os_patch_level }}
      patch_path: "5.10"
  upload-artifacts:
    needs: build-kernel
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      
      - uses: actions/checkout@v3
        with:
          path: KernelSU
          fetch-depth: 0

      - name: List artifacts
        run: |
          tree

      - name: Download prebuilt toolchain
        run: |
          AOSP_MIRROR=https://android.googlesource.com
          BRANCH=master-kernel-build-2022
          git clone $AOSP_MIRROR/platform/prebuilts/build-tools -b $BRANCH --depth 1 build-tools
          git clone $AOSP_MIRROR/kernel/prebuilts/build-tools -b $BRANCH --depth 1 kernel-build-tools
          git clone $AOSP_MIRROR/platform/system/tools/mkbootimg -b $BRANCH --depth 1
      
      - name: Setup mutex for uploading
        uses: ben-z/gh-action-mutex@v1.0-alpha-7
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && steps.need_upload.outputs.UPLOAD == 'true'
        
      - name: Build boot images
        run: |
          AVBTOOL=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/bin/avbtool
          GZIP=$GITHUB_WORKSPACE/build-tools/path/linux-x86/gzip
          LZ4=$GITHUB_WORKSPACE/build-tools/path/linux-x86/lz4
          MKBOOTIMG=$GITHUB_WORKSPACE/mkbootimg/mkbootimg.py
          UNPACK_BOOTIMG=$GITHUB_WORKSPACE/mkbootimg/unpack_bootimg.py
          cd $GITHUB_WORKSPACE/KernelSU
          export VERSION=$(git rev-list --count HEAD)
          echo "VERSION: $VERSION"
          cd -
          bash $GITHUB_WORKSPACE/KernelSU/.github/scripts/buiild_a12.sh

  check-build-kernel:
    needs: build-ksud
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android12-5.10
      version_name: android12-5.10.101
      tag: android12-5.10-2022-05
      patch_path: "5.10"
