name: Build Kernel - Android 12
on:
  push:
    branches: ["main", "ci"]
    paths:
      - ".github/workflows/build-kernel-a12.yml"
      - ".github/workflows/gki-kernel.yml"
      - "kernel/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build-kernel-a12.yml"
      - ".github/workflows/gki-kernel.yml"
      - "kernel/**"
jobs:
  build-ksud:
    uses: ./.github/workflows/ksud.yml
    with:
      target: aarch64-linux-android
  build-kernel:
    needs: build-ksud
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        include:
          - sub_level: 66
            os_patch_level: 2021-11
          - sub_level: 81
            os_patch_level: 2022-03
          - sub_level: 101
            os_patch_level: 2022-05
          - sub_level: 110
            os_patch_level: 2022-07
          - sub_level: 136
            os_patch_level: 2022-11
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android12-5.10
      version_name: android12-5.10.${{ matrix.sub_level }}
      tag: android12-5.10-${{ matrix.os_patch_level }}
      patch_path: "5.10"
  upload-artifacts:
    needs: build-kernel
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      
      - name: List artifacts
        run: |
          tree

      - name: Upload to telegram
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CACHE_CHAT_ID: ${{ secrets.CACHE_CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TITLE: kernel-${{ inputs.version_name }}
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            cd $GITHUB_WORKSPACE/KernelSU
            export VERSION=$(git rev-list --count HEAD)
            cd -
            pip3 install python-telegram-bot
            find . -type f -name "Image-" | xargs python3 $GITHUB_WORKSPACE/KernelSU/scripts/ksubot.py
          fi
  check-build-kernel:
    needs: build-ksud
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android12-5.10
      version_name: android12-5.10.101
      tag: android12-5.10-2022-05
      patch_path: "5.10"
