name: Build Manager
on:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/build-manager.yml'
      - 'manager/**'
      - 'userspace/ksud/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'manager/**'
  workflow_call:
jobs:
  build-ksud:
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
          - target: x86_64-linux-android
    uses: ./.github/workflows/ksud.yml
    with:
      target: ${{ matrix.target }}
  build-manager:
    needs: build-ksud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manager
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup need_upload
      id: need_upload
      run: |
        if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          echo "UPLOAD=true" >> $GITHUB_OUTPUT
        else
          echo "UPLOAD=false" >> $GITHUB_OUTPUT
        fi
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        local-cache: true
    - name: Extract keystore
      if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/main' ) || github.ref_type == 'tag' }}
      run: |
        if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
          echo KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' >> sign.properties
          echo KEY_ALIAS='${{ secrets.KEY_ALIAS }}' >> sign.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> sign.properties
          echo KEYSTORE_FILE='../key.jks' >> sign.properties
          echo ${{ secrets.KEYSTORE }} | base64 --decode > key.jks
        fi
    - name: Download arm64 ksud
      uses: actions/download-artifact@v3
      with:
        name: ksud-aarch64-linux-android
        path: .
    - name: Download x86_64 ksud
      uses: actions/download-artifact@v3
      with:
        name: ksud-x86_64-linux-android
        path: .
    - name: Copy ksud to app jniLibs
      run: |
        mkdir -p app/src/main/jniLibs/arm64-v8a
        mkdir -p app/src/main/jniLibs/x86_64
        cp -f ../aarch64-linux-android/release/ksud ../manager/app/src/main/jniLibs/arm64-v8a/libksud.so
        cp -f ../x86_64-linux-android/release/ksud ../manager/app/src/main/jniLibs/x86_64/libksud.so
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean assembleRelease
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: manager
        path: manager/app/build/outputs/apk/release/*.apk
    - name: Setup mutex for uploading
      uses: ben-z/gh-action-mutex@v1.0-alpha-7
      if: github.event_name != 'pull_request' && steps.need_upload.outputs.UPLOAD == 'true'
    - name: Upload to telegram
      if: github.event_name != 'pull_request' && steps.need_upload.outputs.UPLOAD == 'true'
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        CACHE_CHAT_ID: ${{ secrets.CACHE_CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        TITLE: Manager
      run: |
        if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          export VERSION=$(git rev-list --count HEAD)
          APK=$(find ./app/build/outputs/apk/release -name "*.apk")
          pip3 install python-telegram-bot
          python3 $GITHUB_WORKSPACE/scripts/ksubot.py $APK
        fi
