name: Build Kernel 5.15
on:
  push:
    branches: ["main", "ci"]
    paths:
      - ".github/workflows/build-kernel-5.15.yml"
      - ".github/workflows/gki-kernel.yml"
      - "kernel/**"
  pull_request:
    branches: ["main"]
    paths:
      - "kernel/**"
jobs:
  build:
    strategy:
      matrix:
        include:
          - version: 41
            os_patch_level: 2022-11
          - version: 74
            os_patch_level: 2022-12
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android13-5.15
      version_name: android13-5.15-${{ matrix.version }}
      tag: android13-5.15-${{ matrix.os_patch_level }}
      os_version: 13.0.0
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: 5.15
