name: Build Userspace
on:
  push:
    branches: [ "main", "fix-ci" ]
    paths: 
      - '.github/workflows/build-userspace.yml'
      - 'userspace/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'userspace/**'
jobs:
  build-su:
    name: Build userspace su
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        local-cache: true
    - name: Build su
      working-directory: ./userspace/su
      run: ndk-build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: su
        path: ./userspace/su/libs
  build-arm64-ksud:
    name: Build ksud for arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build aarch64 ksud
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        target: aarch64-linux-android
        override: true
    - name: setup cargo
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target aarch64-linux-android --release --manifest-path ./userspace/ksud/Cargo.toml
    - name: Upload aarch64 ksud Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ksud-arm64
        path: ./userspace/ksud/target/aarch64-linux-android/release/ksud
  build-x86_64-ksud:
    name: Build ksud for x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build x86_64 ksud
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        target: x86_64-linux-android
        override: true
    - name: setup cargo
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target x86_64-linux-android --release --manifest-path ./userspace/ksud/Cargo.toml
    - name: Upload aarch64 ksud Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ksud-arm64
        path: ./userspace/ksud/target/x86_64-linux-android/release/ksud

