name: Build KSUD
on:
  push:
    branches: [ "main", "fix-ci" ]
    paths: 
      - '.github/workflows/build-ksud.yml'
      - 'userspace/ksud/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'userspace/ksud/**'
jobs:
  build:
    name: Build KSUD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build aarch64 ksud
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        target: 
          - aarch64-linux-android
          - x86_64-linux-android
        override: true
    - name: setup cargo
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target aarch64-linux-android --target x86_64-linux-android --release --manifest-path ./userspace/ksud/Cargo.toml
    - name: Upload ksud Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ksud-arm64
        path: ./userspace/ksud/target/**/release/ksud

