name: Build ksud
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup rustup
      run: |
        rustup update stable
  
    - name: Install cross
      run: |
        cargo install cross --git https://github.com/cross-rs/cross --rev 66845c1

    - name: Build ksud
      run: CROSS_NO_WARNINGS=0 cross build --target aarch64-linux-android --release --manifest-path ./userspace/ksud/Cargo.toml

    - name: Upload ksud artifact
      uses: actions/upload-artifact@v4
      with:
        name: ksud-aarch64-linux-android
        path: userspace/ksud/target/**/release/ksud*
