# GitHub Actions workflow for automatically closing pull requests
# This workflow is specific to Blender's GitHub mirror and directs contributors to the official development platform on blender.org

name: Close GitHub Pull Requests

# Trigger this workflow every 12 hours.
on:
  pull_request:

jobs:
  close_prs:
    name: Close Pull Requests
    runs-on: ubuntu-latest
    # Only run this job in the read-only mirror repository.
    if: github.repository == 'blender/blender' && contains(github.server_url, 'github.com')
    # Permissions granted to the GitHub Actions bot.
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          # Number of days before a pull request is marked as stale.
          days-before-pr-stale: 0
          # Number of days before a pull request is closed.
          days-before-pr-close: 0
          # Message posted when closing a pull request.
          stale-pr-message: |
            This pull request has been automatically closed.
            Because this project won't accept any pull requests that include bug fixes and feature improvements.
            See README.md for more details.
